# Generated by Django 2.1.3 on 2018-12-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(max_length=20)),
                ('pas', models.CharField(max_length=20)),
                ('nam', models.CharField(max_length=20)),
                ('sur', models.CharField(max_length=20)),
                ('age', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(max_length=20)),
                ('pas', models.CharField(max_length=20)),
                ('nam', models.CharField(max_length=20)),
                ('sur', models.CharField(max_length=20)),
                ('fac', models.CharField(max_length=20)),
                ('age', models.PositiveIntegerField()),
            ],
        ),
    ]
