# Generated by Django 2.1.3 on 2018-12-19 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Citybus1', '0003_auto_20181219_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sou', models.CharField(max_length=30)),
                ('des', models.CharField(max_length=30)),
                ('dep', models.CharField(max_length=20)),
                ('arr', models.CharField(max_length=20)),
                ('pri', models.PositiveIntegerField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Citybus1.Bus')),
                ('dri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Citybus1.Driver')),
            ],
        ),
    ]
